apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-keycloakdemo
  namespace: mfi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-keycloakdemo
  template:
    metadata:
      labels:
        app: deploy-keycloakdemo
    spec:
      containers:
      - name: deploy-keycloakdemo
        image: maheshlakade148/keycloak:4.8.3.Final.0
        ports:
        - containerPort: 8080
        env:
        - name: DEMO_GREETING
          value: "Hello from the environment"
        - name: DB_VENDOR
          value: "POSTGRES"
        - name: DB_ADDR
          value: "postgresdemo"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "keycloak"
        - name: DB_USER
          value: "keycloak"
        - name: DB_PASSWORD
          value: "password"
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"

---
apiVersion: v1
kind: Service
metadata: 
  name: keycloakdemo
  namespace: mfi-dev
spec: 
  selector: 
    app: deploy-keycloakdemo
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP  
#  type: LoadBalancer
#  type: ClusterIP

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-postgresdemo
  namespace: mfi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-postgresdemo
  template:
    metadata:
      labels:
        app: deploy-postgresdemo
    spec:
      containers:
      - name: deploy-postgresdemo
        image:  postgres:9.6 
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "keycloak"
        - name: POSTGRES_USER
          value: "keycloak"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DATABASE
          value: keycloak
        - name: POSTGRES_ROOT_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata: 
  name: postgresdemo
  namespace: mfi-dev
spec: 
  selector: 
    app: deploy-postgresdemo
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP  
  type: ClusterIP

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-kongdemo
  namespace: mfi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-kongdemo
  template:
    metadata:
      labels:
        app: deploy-kongdemo
    spec:
      containers:
      - name: deploy-kongdemo
        image: maheshlakade148/kong:1.2.1.1
        ports:
        - containerPort: 8000
        - containerPort: 8001
        env:
        - name: DEMO_GREETING
          value: "Hello from the environment"
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: "kongpostgresdemo"
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_DATABASE
          value: "api-gw"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value:  "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value:  "/dev/stderr"
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        - name: KONG_PLUGINS
          value:  "oidc"
        - name: KONG_PG_PASSWORD
          value: "kong123"
---
apiVersion: v1
kind: Service
metadata: 
  name: kongdemo
  namespace: mfi-dev
spec: 
  selector: 
    app: deploy-kongdemo
  ports:
  - name: proxy
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: admin
    port: 8001
    targetPort: 8001
    protocol: TCP
#  type: LoadBalancer
#  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-kongpostgresdemo
  namespace: mfi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-kongpostgresdemo
  template:
    metadata:
      labels:
        app: deploy-kongpostgresdemo
    spec:
      containers:
      - name: deploy-kongpostgresdemo
        image:  postgres:9.6 
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "api-gw"
        - name: POSTGRES_USER
          value: "kong"
        - name: POSTGRES_PASSWORD
          value: "kong123"
---
apiVersion: v1
kind: Service
metadata: 
  name: kongpostgresdemo
  namespace: mfi-dev
spec: 
  selector: 
    app: deploy-kongpostgresdemo
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP  
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginxpostgresdemo
  namespace: mfi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-nginxpostgresdemo
  template:
    metadata:
      labels:
        app: deploy-nginxpostgresdemo
    spec:
      containers:
      - name: deploy-nginxpostgresdemo
        image:  postgres:9.6 
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "keycloak"
        - name: POSTGRES_USER
          value: "keycloak"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DATABASE
          value: keycloak
        - name: POSTGRES_ROOT_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata: 
  name: nginxpostgresdemo
  namespace: mfi-dev
spec: 
  selector: 
    app: deploy-nginxpostgresdemo
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP  
  type: ClusterIP

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-springdemo
  namespace: mfi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-springdemo
  template:
    metadata:
      labels:
        app: deploy-springdemo
    spec:
      containers:
      - name: deploy-springdemo
        image: maheshlakade148/spring:1.0.0
        ports:
        - containerPort: 8080
        env:

---
apiVersion: v1
kind: Service
metadata: 
  name: springdemo
  namespace: mfi-dev
spec: 
  selector: 
    app: deploy-springdemo
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP  
#  type: LoadBalancer
#  type: ClusterIP
